export const demoData = {
  items: [
    {
      dialed_number: "+18008132279",
      group_full_name: "test",
      group_name: "test",
      main_greeting: "test",
      after_hr_msg: "Sorry we are closed no call us during our working hours",
      enable_emergency_flg: true,
      no_agents_logged_in_flg: true,
      agents_unstaffed_flg: false,
      enable_callback_flg: true,
      enable_spcl_condtn_flg: true,
      spcl_condtn_msg: "test",
      route_call_to_queue: "test",
      queue_msg: "test",
      extn_num: "test",
      play_menu_optns_flg: "test",
      menu_optn_msg: "test",
      queue_arn: "test",
      voice_mail_flg: "test",
      last_update_by: "test",
      last_update_date: "2022-12-25T18:18:13.683Z",
      hours_of_operations_name: "test",
      voice_mail_destn_email: "test",
      createdAt: "2022-11-30T14:35:20.009Z",
      updatedAt: "2022-11-30T14:35:20.009Z",
    },
    {
      dialed_number: "123456",
      group_full_name: "null",
      group_name: "null",
      main_greeting: "1235",
      after_hr_msg: "Welcome",
      enable_emergency_flg: false,
      no_agents_logged_in_flg: true,
      agents_unstaffed_flg: false,
      enable_callback_flg: false,
      enable_spcl_condtn_flg: false,
      spcl_condtn_msg: "true",
      route_call_to_queue: "false",
      queue_msg: "hello world",
      extn_num: "1324",
      play_menu_optns_flg: "false",
      menu_optn_msg: "hello world",
      queue_arn: null,
      voice_mail_flg: "false",
      last_update_by: "null",
      last_update_date: "2022-11-30T08:21:56.696Z",
      hours_of_operations_name: null,
      voice_mail_destn_email: null,
      createdAt: "2022-11-30T08:22:06.830Z",
      updatedAt: "2022-11-30T08:22:06.830Z",
    },
    {
      dialed_number: "asdg",
      group_full_name: null,
      group_name: null,
      main_greeting: "hello world",
      after_hr_msg: "",
      enable_emergency_flg: false,
      no_agents_logged_in_flg: false,
      agents_unstaffed_flg: false,
      enable_callback_flg: false,
      enable_spcl_condtn_flg: false,
      spcl_condtn_msg: "false",
      route_call_to_queue: "false",
      queue_msg: "",
      extn_num: "",
      play_menu_optns_flg: "false",
      menu_optn_msg: "",
      queue_arn: null,
      voice_mail_flg: "false",
      last_update_by: null,
      last_update_date: null,
      hours_of_operations_name: null,
      voice_mail_destn_email: null,
      createdAt: "2022-11-30T08:43:28.390Z",
      updatedAt: "2022-11-30T08:43:28.390Z",
    },
    {
      dialed_number: "12345674563454w",
      group_full_name: "null",
      group_name: "null",
      main_greeting: "hello world",
      after_hr_msg: "",
      enable_emergency_flg: false,
      no_agents_logged_in_flg: false,
      agents_unstaffed_flg: false,
      enable_callback_flg: false,
      enable_spcl_condtn_flg: false,
      spcl_condtn_msg: "false",
      route_call_to_queue: "false",
      queue_msg: "",
      extn_num: "",
      play_menu_optns_flg: "false",
      menu_optn_msg: "",
      queue_arn: null,
      voice_mail_flg: "false",
      last_update_by: "null",
      last_update_date: "2022-11-30T08:38:03.089Z",
      hours_of_operations_name: null,
      voice_mail_destn_email: null,
      createdAt: "2022-11-30T08:38:06.393Z",
      updatedAt: "2022-11-30T08:38:06.393Z",
    },
    {
      dialed_number: "345fdsa456",
      group_full_name: null,
      group_name: null,
      main_greeting: "asdf",
      after_hr_msg: "",
      enable_emergency_flg: false,
      no_agents_logged_in_flg: false,
      agents_unstaffed_flg: false,
      enable_callback_flg: false,
      enable_spcl_condtn_flg: false,
      spcl_condtn_msg: "false",
      route_call_to_queue: "false",
      queue_msg: "32rq",
      extn_num: "2314",
      play_menu_optns_flg: "false",
      menu_optn_msg: "hello world",
      queue_arn: null,
      voice_mail_flg: "false",
      last_update_by: "sbharadwaj@intervision.com",
      last_update_date: "2022-11-30T09:00:30.127Z",
      hours_of_operations_name: null,
      voice_mail_destn_email: null,
      createdAt: "2022-11-30T09:00:29.653Z",
      updatedAt: "2022-11-30T09:00:29.653Z",
    },
    {
      dialed_number: "1242224",
      group_full_name: null,
      group_name: null,
      main_greeting: "hello world",
      after_hr_msg: "true",
      enable_emergency_flg: true,
      no_agents_logged_in_flg: true,
      agents_unstaffed_flg: true,
      enable_callback_flg: true,
      enable_spcl_condtn_flg: true,
      spcl_condtn_msg: "true",
      route_call_to_queue: "true",
      queue_msg: "hello world",
      extn_num: "hello world",
      play_menu_optns_flg: "true",
      menu_optn_msg: "hello world",
      queue_arn: null,
      voice_mail_flg: "true",
      last_update_by: null,
      last_update_date: null,
      hours_of_operations_name: null,
      voice_mail_destn_email: null,
      createdAt: "2022-11-30T06:58:09.722Z",
      updatedAt: "2022-11-30T06:58:09.722Z",
    },
    {
      dialed_number: "test",
      group_full_name: "test",
      group_name: "test",
      main_greeting: "test",
      after_hr_msg: " test",
      enable_emergency_flg: true,
      no_agents_logged_in_flg: true,
      agents_unstaffed_flg: true,
      enable_callback_flg: true,
      enable_spcl_condtn_flg: true,
      spcl_condtn_msg: "test",
      route_call_to_queue: "test",
      queue_msg: "test",
      extn_num: "test",
      play_menu_optns_flg: "test",
      menu_optn_msg: "test",
      queue_arn: null,
      voice_mail_flg: "test",
      last_update_by: "test",
      last_update_date: "2022-12-25T18:18:13.683Z",
      hours_of_operations_name: null,
      voice_mail_destn_email: null,
      createdAt: "2022-11-30T08:04:54.943Z",
      updatedAt: "2022-11-30T08:04:54.943Z",
    },
    {
      dialed_number: "124222467890",
      group_full_name: "null",
      group_name: "null",
      main_greeting: "hello world",
      after_hr_msg: "Welcome",
      enable_emergency_flg: false,
      no_agents_logged_in_flg: false,
      agents_unstaffed_flg: false,
      enable_callback_flg: false,
      enable_spcl_condtn_flg: false,
      spcl_condtn_msg: "false",
      route_call_to_queue: "false",
      queue_msg: "hello world",
      extn_num: "1324",
      play_menu_optns_flg: "false",
      menu_optn_msg: "hello world",
      queue_arn: null,
      voice_mail_flg: "false",
      last_update_by: "null",
      last_update_date: "2022-11-30T08:36:23.773Z",
      hours_of_operations_name: null,
      voice_mail_destn_email: null,
      createdAt: "2022-11-30T08:36:28.815Z",
      updatedAt: "2022-11-30T08:36:28.815Z",
    },
    {
      dialed_number: "asdfasdaasdf",
      group_full_name: null,
      group_name: null,
      main_greeting: "hello world",
      after_hr_msg: "",
      enable_emergency_flg: false,
      no_agents_logged_in_flg: false,
      agents_unstaffed_flg: false,
      enable_callback_flg: false,
      enable_spcl_condtn_flg: false,
      spcl_condtn_msg: "false",
      route_call_to_queue: "false",
      queue_msg: "",
      extn_num: "12413",
      play_menu_optns_flg: "false",
      menu_optn_msg: "hello world",
      queue_arn: null,
      voice_mail_flg: "false",
      last_update_by: "sbharadwaj@intervision.com",
      last_update_date: "2022-11-30T08:59:06.982Z",
      hours_of_operations_name: null,
      voice_mail_destn_email: null,
      createdAt: "2022-11-30T08:59:07.182Z",
      updatedAt: "2022-11-30T08:59:07.182Z",
    },
  ],
  nextToken: null,
};
